### ISSUE TITLE
where does this store data

### ISSUE THREAD

**Issue by Hellscaped** [GooseMod/Extension#2]

**Comment by yellowsink** [comment]
Your browser's localStorage.

You can see it in devtools if you like.

**Comment by yellowsink** [comment]
To clarify this is where goosemod itself stores the data, the extension just injects it.
GM also uses localStorage on a discord app install.

**Comment by CanadaHonk** [comment]
GM primarily uses extension storage, as well as localStorage and, if on desktop, userDataCache as backups. Please use the Discord for questions, GitHub issues is for issues, not discussion or support.

**Comment by yellowsink** [comment]
It doesn't? Huh.
________________________________
